server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - AddRequestHeader=Authorization, "#{RequestHeaders.Authorization}"
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**, /internal/users/**
          filters:
            - AddRequestHeader=Authorization, "#{RequestHeaders.Authorization}"